# Generated by Django 2.0.1 on 2018-02-01 16:44

from django.db import migrations, models
import notatetr.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('slug', models.CharField(default=notatetr.models.generate_id, max_length=10)),
            ],
        ),
    ]
