# Generated by Django 2.0.1 on 2018-02-01 19:47

from django.db import migrations, models
import notatetr.models


class Migration(migrations.Migration):

    dependencies = [
        ('notatetr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.CharField(default=notatetr.models.generate_id, max_length=100),
        ),
    ]
