# Generated by Django 2.0.1 on 2018-02-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notatetr', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='slug',
            field=models.CharField(default='734265235<django.db.models.fields.related.ForeignKey>', max_length=100),
        ),
    ]
